# Generated by Django 5.0.2 on 2024-03-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('inscriptionDate', models.DateField()),
                ('ciNumber', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('fatherPhone', models.CharField(max_length=20)),
                ('motherPhone', models.CharField(max_length=20)),
            ],
        ),
    ]
