# Generated by Django 4.2.10 on 2024-03-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('S', 'Sábado')], max_length=1)),
                ('section', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fee_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('days_per_week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
