# Generated by Django 5.0.2 on 2024-03-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
