# Generated by Django 5.0.2 on 2024-03-17 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course'),
        ('students', '0002_student_email'),
    ]

    operations = [
    ]
