# Generated by Django 5.0.2 on 2024-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_merge_0002_course_0002_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
