# Generated by Django 5.0.2 on 2024-03-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
