# Generated by Django 5.0.2 on 2024-03-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_course_subjects'),
        ('subjects', '0002_subject_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='subjects.subject'),
        ),
    ]
