# Generated by Django 5.0.2 on 2024-04-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_course_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='inscriptionDate',
        ),
    ]
