# Generated by Django 5.0.3 on 2024-04-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_course_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('xyz_puede_ver_cursos', 'Puede ver cursos'), ('xyz_puede_crear_cursos', 'Puede crear cursos'), ('xyz_puede_modificar_cursos', 'Puede modificar cursos'), ('xyz_puede_eliminar_cursos', 'Puede eliminar cursos')]},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('xyz_puede_ver_estudiantes', 'Puede ver estudiantes'), ('xyz_puede_crear_estudiantes', 'Puede crear estudiantes'), ('xyz_puede_modificar_estudiantes', 'Puede modificar estudiantes'), ('xyz_puede_eliminar_estudiantes', 'Puede eliminar estudiantes')]},
        ),
    ]
