# Generated by Django 5.0.2 on 2024-04-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_course_options_alter_student_options'),
        ('students', '0011_remove_student_course_remove_student_inscriptiondate'),
    ]

    operations = [
    ]
