# Generated by Django 5.0.2 on 2024-04-26 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('countries', '0002_country_active'),
        ('students', '0012_merge_20240426_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.country'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.cities'),
        ),
    ]
