# Generated by Django 5.0.4 on 2024-05-02 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_country_alter_student_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
            options={
                'permissions': [('xyz_puede_ver_secciones', 'Puede ver secciones'), ('xyz_puede_crear_secciones', 'Puede crear secciones'), ('xyz_puede_modificar_secciones', 'Puede modificar secciones'), ('xyz_puede_eliminar_secciones', 'Puede eliminar secciones')],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
            options={
                'permissions': [('xyz_puede_ver_turnos', 'Puede ver turnos'), ('xyz_puede_crear_turnos', 'Puede crear turnos'), ('xyz_puede_modificar_turnos', 'Puede modificar turnos'), ('xyz_puede_eliminar_turnos', 'Puede eliminar turnos')],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.section'),
        ),
        migrations.AlterField(
            model_name='course',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.shift'),
        ),
    ]
