# Generated by Django 5.0.2 on 2024-06-08 13:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days_per_week',
            field=models.IntegerField(),
        ),
    ]
