# Generated by Django 5.0.2 on 2024-06-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_course_days_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days_per_week',
            field=models.IntegerField(),
        ),
    ]
