# Generated by Django 5.0.2 on 2024-06-08 13:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_remove_course_days_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='days_per_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'MONDAY'), (2, 'TUESDAY'), (3, 'WEDNESDAY'), (4, 'THURSDAY'), (5, 'FRIDAY'), (6, 'SATURDAY'), (7, 'SUNDAY')]), blank=True, null=True, size=None),
        ),
    ]
