# Generated by Django 5.0.2 on 2024-06-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_course_days_per_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('courseId', models.ManyToManyField(to='students.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='class_dates',
            field=models.ManyToManyField(blank=True, to='students.coursedates'),
        ),
    ]
