# Generated by Django 5.0.2 on 2024-06-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_coursedates_course_class_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_dates',
        ),
        migrations.RemoveField(
            model_name='coursedates',
            name='courseId',
        ),
    ]
