# Generated by Django 5.0.2 on 2024-06-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_course_class_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedates',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.course'),
        ),
    ]
