# Generated by Django 5.0.2 on 2024-06-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_course_maxstudentsnumber_course_minstudentsnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='matriculation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='matriculation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
