# Generated by Django 5.0.2 on 2024-06-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_course_space_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollment_start_date',
        ),
    ]
