# Generated by Django 5.0.2 on 2024-03-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
