# Generated by Django 5.0.3 on 2024-04-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'permissions': [('xyz_puede_ver_materias', 'Puede ver materias'), ('xyz_puede_crear_materias', 'Puede crear materias'), ('xyz_puede_modificar_materias', 'Puede modificar materias'), ('xyz_puede_eliminar_materias', 'Puede eliminar materias')]},
        ),
    ]
