# Generated by Django 5.0.3 on 2024-03-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_enrollment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(choices=[('enrollment', 'Matrícula'), ('fee', 'Cuota')], default='enrollment', max_length=20),
        ),
    ]
