# Generated by Django 5.0.3 on 2024-04-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymenttype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'permissions': [('xyz_puede_ver_matriculas', 'Puede ver matrículas'), ('xyz_puede_crear_matriculas', 'Puede crear matrículas'), ('xyz_puede_modificar_matriculas', 'Puede modificar matrículas'), ('xyz_puede_eliminar_matriculas', 'Puede eliminar matrículas')]},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'permissions': [('xyz_puede_ver_cuotas', 'Puede ver cuotas'), ('xyz_puede_crear_cuotas', 'Puede crear cuotas'), ('xyz_puede_modificar_cuotas', 'Puede modificar cuotas'), ('xyz_puede_eliminar_cuotas', 'Puede eliminar cuotas')]},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('xyz_puede_ver_pagos', 'Puede ver pagos'), ('xyz_puede_crear_pagos', 'Puede crear pagos'), ('xyz_puede_modificar_pagos', 'Puede modificar pagos'), ('xyz_puede_eliminar_pagos', 'Puede eliminar pagos')]},
        ),
    ]
