# Generated by Django 5.0.4 on 2024-05-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
