# Generated by Django 5.0.4 on 2024-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_rename_fee_remaining_amount_fee_fee_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
