# Generated by Django 5.0.4 on 2024-05-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_enrollment_enrollment_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
