# Generated by Django 5.0.3 on 2024-06-04 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_enrollment_name_fee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.enrollment'),
        ),
    ]
