# Generated by Django 5.0.4 on 2024-06-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_stamping_cashbox_invoice_invoicedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='concept',
        ),
    ]
