# Generated by Django 5.0.3 on 2024-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_invoice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='iva',
            field=models.CharField(choices=[('10', '10%'), ('5', '5%'), ('0', '0%')], default='10', max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='iva_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='iva_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='iva_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
