# Generated by Django 5.0.3 on 2024-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_concept_iva_invoice_iva_10_invoice_iva_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='iva_0',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='iva_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='iva_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
