# Generated by Django 5.0.3 on 2024-06-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_invoicedetail_iva_0_invoicedetail_iva_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='iva_0',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='iva_10',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='iva_5',
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_total_iva_0',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_total_iva_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_total_iva_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
