# Generated by Django 5.0.3 on 2024-06-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_remove_invoicedetail_iva_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='related_to',
            field=models.CharField(choices=[('enrollment', 'Matrícula'), ('fee', 'Cuota'), ('other', 'Otro')], max_length=20, blank=True, null=True),
        ),
    ]
