# Generated by Django 5.0.3 on 2024-06-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_concept_related_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fee',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.enrollment'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.fee'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.invoice'),
        ),
    ]
