# Generated by Django 5.0.3 on 2024-06-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_remove_payment_enrollment_remove_payment_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.enrollment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.fee'),
        ),
    ]
