# Generated by Django 5.0.3 on 2024-06-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_payment_enrollment_payment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamping',
            name='expedition_point',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
