# Generated by Django 5.0.4 on 2024-06-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_alter_stamping_expedition_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='related_to',
            field=models.CharField(blank=True, choices=[('enrollment', 'Matrícula'), ('fee', 'Cuota'), ('other', 'Otro')], max_length=20, null=True),
        ),
    ]
