# Generated by Django 5.0.2 on 2024-06-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_remove_payment_enrollment_remove_payment_fee_and_more'),
        ('students', '0025_rename_matriculation_end_date_course_enrollment_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.student'),
        ),
    ]
