# Generated by Django 5.0.2 on 2024-06-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_remove_enrollment_student_enrollment_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enrollment_amount',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='year',
        ),
    ]
