# Generated by Django 5.0.2 on 2024-06-15 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_remove_enrollment_enrollment_amount_and_more'),
        ('students', '0025_rename_matriculation_end_date_course_enrollment_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='students',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
