# Generated by Django 5.0.4 on 2024-06-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_enrollment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
