# Generated by Django 5.0.4 on 2024-06-22 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_remove_enrollment_enrollment_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='state',
        ),
        migrations.AddField(
            model_name='enrollmentdetail',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentdetail',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.state'),
        ),
    ]
