# Generated by Django 5.0.2 on 2024-06-22 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentdetail',
            name='student_enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
