# Generated by Django 5.0.2 on 2024-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0032_enrollmentdetail_student_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
