# Generated by Django 5.0.3 on 2024-04-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'permissions': [('xyz_puede_ver_asistencias', 'Puede ver asistencias'), ('xyz_puede_crear_asistencias', 'Puede crear asistencias'), ('xyz_puede_modificar_asistencias', 'Puede modificar asistencias'), ('xyz_puede_eliminar_asistencias', 'Puede eliminar asistencias')]},
        ),
    ]
