# Generated by Django 5.0.2 on 2024-06-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_remove_attendance_present_remove_attendance_student_and_more'),
        ('students', '0015_course_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceRecord',
            new_name='AttendanceStudent',
        ),
    ]
