# Generated by Django 5.0.2 on 2024-06-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_rename_attendancerecord_attendancestudent'),
        ('students', '0015_course_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceStudent',
            new_name='AttendanceRecord',
        ),
    ]
