# Generated by Django 5.0.2 on 2024-06-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0007_attendance_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='students',
        ),
    ]
