# Generated by Django 5.0.2 on 2024-06-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0008_remove_attendance_students'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='AttendanceRecord',
        # ),
    ]
