# Generated by Django 5.0.2 on 2024-06-08 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0010_attendance_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='students',
        ),
        # migrations.DeleteModel(
        #     name='AttendanceRecord',
        # ),
    ]
