# Generated by Django 5.0.2 on 2024-06-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0012_delete_attendancerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
