# Generated by Django 5.0.2 on 2024-06-08 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0013_delete_attendancerecord'),
        ('students', '0022_coursedates_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendances.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(through='attendances.AttendanceStudent', to='students.student'),
        ),
    ]
