# Generated by Django 5.0.2 on 2024-06-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0014_attendancestudent_attendance_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestudent',
            name='present',
            field=models.BooleanField(blank=True),
        ),
    ]
