# Generated by Django 5.0.2 on 2024-06-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0015_alter_attendancestudent_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestudent',
            name='present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
