# Generated by Django 5.0.2 on 2024-06-13 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0016_alter_attendancestudent_present'),
        ('students', '0023_course_maxstudentsnumber_course_minstudentsnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
