# Generated by Django 4.2.10 on 2024-06-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0017_alter_attendancestudent_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic_email', models.BooleanField(default=True)),
            ],
        ),
    ]
