# Generated by Django 5.0.2 on 2024-03-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customgroup_remove_userroles_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
