# Generated by Django 5.0.3 on 2024-04-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userlogin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('xyz_puede_ver_persona', 'Puede ver personas'), ('xyz_puede_agregar_persona', 'Puede agregar personas'), ('xyz_puede_modificar_persona', 'Puede modificar personas'), ('xyz_puede_eliminar_persona', 'Puede eliminar personas')]},
        ),
    ]
