# Generated by Django 5.0.4 on 2024-05-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
