# Generated by Django 5.0.4 on 2024-07-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userlogin_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
