# Generated by Django 5.0.3 on 2024-07-27 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_person_active'),
        ('students', '0027_remove_course_enrollment_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
